Ensure fast exit
greatscottgadgets/hackrf pull request #1063
Opened 2022-03-15 12:58 UTC by metayan

transfer_threadproc has a timeout of half a second, so
when kill_transfer_thread tries to pthread_join, it often
has to wait until the timeout kicks in.

With this fix, we ensure that a final request is made after
request_exit has been called, so that transfer_threadproc can exit its
loop in a fast and clean manner.

2022-03-16 10:23 UTC, martinling requested changes
You don't need to send an unnecessary USB request to wake up the libusb thread - you can use [`libusb_interrupt_event_handler`](https://libusb.sourceforge.io/api-1.0/group__libusb__poll.html#ga188b6c50944b49f122ccfd45b93fa9f2).

2022-03-16 10:25 UTC, metayan commented
> You don't need to send an unnecessary USB request to wake up the libusb thread - you can use [`libusb_interrupt_event_handler`](https://libusb.sourceforge.io/api-1.0/group__libusb__poll.html#ga188b6c50944b49f122ccfd45b93fa9f2).

Ah, excellent. Thanks. I'll change it. And test it.

2022-03-16 11:43 UTC, metayan commented
Using `libusb_interrupt_event_handler` now. Thanks for the tip.

2022-03-17 12:07 UTC, martinling approved these changes
Great fix, thanks!

2022-03-17 12:07 UTC, merged

2022-03-17 12:14 UTC, metayan commented
You're welcome. Just a tiny speck of polish on your great work…
Took a while to figure out, though. ;)

2022-03-20 11:32 UTC, martinling commented
@metayan if you're trying to optimise timing further, I have another "speck of polish" in PR #1070 that may save some further milliseconds at shutdown.