Update Opera Cake docs
greatscottgadgets/hackrf pull request #1205
Opened 2022-10-24 19:21 UTC by straithe

2022-10-27 00:14 UTC, mossmann requested changes
I love the breakout of the Opera Cake content, but I would like to see a change or two.

2022-10-27 00:14 UTC, mossmann commented on docs/source/index.rst
> +   :caption: HackRF User Documentation
I'm confused by the name change to "HackRF User Documentation", especially with Jawbreaker being moved out of this section. It kind of looks like you meant it to be "HackRF One" not "HackRF", but a lot of the content in this section is relevant to all three HackRF platforms, not just HackRF One. The word "HackRF" does not appear in the name of any other section even though they are all directly related to HackRF (except arguably the Opera Cake section).

2022-10-27 00:14 UTC, mossmann commented on docs/source/index.rst
> +   jawbreaker
I don't like moving the Jawbreaker page away from the HackRF One page unless you plan to also move HackRF One to its own section. At a later time I think we should add a page for rad1o which is the third HackRF platform supported by the software in this repo. I would like either each platform to have its own section or all three platforms to be in the same section.

I notice that the "Hardware" section is almost entirely about HackRF One and could be converted to a HackRF One section. If you are okay with doing that in the future, then I am okay with moving Jawbreaker here.

2022-10-28 19:25 UTC, straithe commented on docs/source/opera_cake_hardware.rst
> +Hardware
Thanks!

2022-10-28 19:38 UTC, straithe commented
Changes made! Thank you for the review.

2023-01-05 12:40 UTC, mossmann approved these changes
Wonderful! Thank you!

2023-01-05 12:40 UTC, merged