HackRF One r9
greatscottgadgets/hackrf pull request #1215
Opened 2022-10-30 14:01 UTC by mossmann

Major changes in this hardware revision:

- change U19 from Si5351C to Si5351A plus external clock distribution
- change U17 from MAX2837 to MAX2839
- add reverse current protection diode to antenna port power supply
- change PCB stack-up
- update design to KiCad 6

2023-01-07 18:27 UTC, mossmann commented
@straithe I would like you to review the block diagrams and other documentation updates.

2023-01-10 22:54 UTC, straithe requested changes
Great work! Just one change requested.

2023-01-10 22:54 UTC, straithe commented on docs/source/hardware_components.rst
> +Block Diagrams
Please add subheadings for each of the blog diagrams in this section. My suggestion is that you use "HackRF One R1-R8 Block Diagram" as the first subheading and "HackRF One R9 Block Diagram" as the second sub heading.

2023-02-01 05:18 UTC, straithe approved these changes
Great job!

2023-02-01 05:18 UTC, merged